name: Package and Release
on:
  push:
    tags:
     - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.TOKEN_CURSE }}
      GITHUB_OAUTH: ${{ secrets.TOKEN_GITHUB }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: WoW Packager
        uses: BigWigsMods/packager@v2
